### ISSUE TITLE
Enhancement Request: Upload Profiles

### ISSUE THREAD

**Issue by gregwaehner** [nightscout/android-uploader#114]
With the increased use of REST API for multiple sites, and the increased use of changing from "this configuration" to "that configuration", this enhancement request is to create and store a profile for a site  with the REST API configuration, and then the REST API "base URL" could simply be "checkbox'ing" which one or more to do... This would simplify / mask the "make sure there's a space between configuration elements, allow for one or more sites, allow for quick testing and configuration changes, etc.

**Comment by ktind** [comment]
Closing per our conversation. Auto-configure seems to satisfy this need. Please re-open this ticket if your enhancement request was not fulfilled with this feature.
