### ISSUE TITLE
REST API format and implications on Release Strategy

### ISSUE THREAD

**Issue by gregwaehner** [nightscout/android-uploader#115]
Beta Uploader REST API format has been refactored into "https://secret@url" instead of previous "secret@https://url". While the dev branch of "cgm-remote-monitor" supports both formats of the REST API, the current 0.5.1 and prior do not. As such, the release of the new uploader will break all nightscout websites running 0.5.1 or prior which use REST API.

In order to deploy new formatting of REST API, new "cgm-remote-monitor" must be deployed and the actual software release/deployment of the uploader CAN NOT be automatic push from Google Play because of the dependency on the new cgm-remote-monitor version.

**Comment by ktind** [comment]
PR #111 should address this issue. @gregwaehner can you confirm that it is working?

**Comment by gregwaehner** [comment]
Confirmed working.
