### ISSUE TITLE
Nexus 9 (Lollipop) upload / connectivity issues

### ISSUE THREAD

**Issue by cjbeck** [nightscout/android-uploader#123]
I'm having issues getting the Dexcom update on a regular basis with my Nexus 9 (non-rooted). My previous Nexus 7 running Lollipop worked perfectly fine, but for some reason the Nexus 9 is not working as well. Are there any special settings I have to enable to get it to stay connected to the Dexcom?

**Comment by ktind** [comment]
Which version are you running?

**Comment by cjbeck** [comment]
I used both the version in the play store, and tried a custom compiled one from the 1.1.11-b2 branch. Both had the same issue.

I suspect it has something to do with the Nexus 9 specifically, since it appears to do something different with OTG vs the Nexus 7 (as seen in this video: https://www.youtube.com/watch?v=_ebxMuMaVzQ). It's hard to find specific information between the two though.

**Comment by cjbeck** [comment]
Is it possible that the "system suspend" is the issue? Maybe the android-updater needs to do something in order to keep the tablet from sleeping in order to pull the values from the Dexcom?

https://source.android.com/devices/tech/power.html#component-power

**Comment by ktind** [comment]
We [obtain a wakelock](https://github.com/nightscout/android-uploader/blob/release/0.1.11-b2/app/src/main/java/com/nightscout/android/dexcom/SyncingService.java#L130) before polling the device. That should prevent the device from suspending during a poll.

Could you use the feedback button after seeing the issue? Perhaps there is something in the logcat that can clue us in.

**Comment by cjbeck** [comment]
Sure can. I'll do it tonight.

**Comment by cjbeck** [comment]
I did the feedback twice last night. Once with a non-root attempt that was stalled for over an hour, and again with a rooted attempt that was stalled for 30ish minutes. It's 100% repeatable. Plug in, initial sync works (though takes a while to get going), and after I lock the screen, it stalls out. Even after I unlock the screen, it stays stalled until I do a "gap sync".

**Comment by ktind** [comment]
Thank you. We got the logs and I was able to find your reports. You may be on to something with regards to power management. In the past, I've always seen an msm_otg wake lock created when an OTG device was connected. I think we've relied on that wakelock heavily with our polling mechanism. This device may not create that wakelock for whatever reason - which might actually be a good thing with regards to battery life. :smiley:

I have an idea that I'd like to try if you're willing help test. I'll create a special build and email you instructions to the address attached to your Github account if that is okay. It'll have to be later this evening though.

**Comment by bhandfast** [comment]
This might be a different issue, but I wanted to use the device without keeping the app visible. And I had a issue with lost syncs when the activity wasn't on screen. So I rewrote the SyncingService to use the alarm manager to schedule next uploads. I have only tested this on a rooted Nexus 5 though...

https://github.com/bhandfast/android-uploader/tree/background-service

**Comment by cjbeck** [comment]
I don't have the OTG connected right now, so probably not a great test...

:g//p
  6   mWakefulness=Asleep
 19   mWakeLockSummary=0x0
 26   mLastWakeTime=14008758 (256058 ms ago)
 32   mHoldingWakeLockSuspendBlocker=false
 38   mWakeUpWhenPluggedOrUnpluggedConfig=true
 79 Wake Locks: size=0
 82   PowerManagerService.WakeLocks: ref count=0

**Comment by cjbeck** [comment]
I'll rerun tonight after I get the Dexcom connected and see if it's
different.

**Comment by ktind** [comment]
And that is precisely what I was going to test @bhandfast :smiley: 

I am not familiar with AlarmManagerCompat. I know [JB introduced a change to the alarm manager](https://developer.android.com/about/versions/android-4.4.html#Behaviors) to be inexact by default with batching. You have to explicitly call setExact if you need more precision on JB+. I'm guessing AlarmManagerCompat handles that? I can't seem to find any documentation on it with a quick search.

We've been toying with the idea of converting the intent service to a service but I'm not sure it will be needed with one of our next steps (event bus).

**Comment by bhandfast** [comment]
Yeah, AlarmManagerCompat is something I wrote to handle the change in behavior from KK+. It doesn't do much more than a couple of ifs. :)

Well I was thinking about making the service bindable in the activity and let the activity talk directly to the service, but I haven't implemented that, and I'm not sure I will. My changes right now could really be in a IntentService only.

**Comment by cjbeck** [comment]
So, if there's any value, I can load up that branch to see if it syncs
better with the N9? I have root on it, so that's not an issue.

**Comment by ktind** [comment]
@cjbeck , can you confirm that the provided fix has resolved the issue?

**Comment by cjbeck** [comment]
Its been working great! Thanks!

**Comment by ktind** [comment]
Submitted PR #127

**Comment by trhodeos** [comment]
This is in the Dreamsicle release. Closing.
