### ISSUE TITLE
update Battery pebble

### ISSUE THREAD

**Issue by francescaneri** [nightscout/android-uploader#133]
since there is the new update does not work anymore. by check please. Matteo

**Comment by francescaneri** [comment]
![image](https://cloud.githubusercontent.com/assets/9915825/5941161/474f9cd0-a70f-11e4-9275-3463664c8bed.jpg)

**Comment by ELUTE** [comment]
Try deleting the documents in your devicestatus collection to resolve this.

**Comment by francescaneri** [comment]
solved . thank you
