### ISSUE TITLE
dreamsicle 0.1.12 not working when an android tablet is the uploader

### ISSUE THREAD

**Issue by gangfc** [nightscout/android-uploader#147]
Hi,
At night we use a tablet as the uploader when the cell phone is re-charging.  I have used my tablet in past running at least 3 different versions of the uploader sucessfully and they all worked before.  There are 2 new problems with this release.
1. When I connect the dex it uploads a couple readings but then about 30 minutes later I it stops working (stops uploading). It does not upload any more readings unless I disconnect and re-connect. I looked at all the settings and the dex with a fine tooth comb all my settings are perfect.  It seems to almost exit out of the loop which uploads readings and yes my cables are fine.  The tablet runs android version 4.1.1
2. When I touch the icon for preferences and select close, to close gracefully the android application crashes. 

I know it's hard to test on a lot  of devices,  but I think android tablets are a critical use case for a lot of people as they make great uploaders when a phone is charging.  Please let me know if I can assist I have crash reporting turned on. Right now I am dropping back to an earlier release.

**Comment by ktind** [comment]
Hi @gangfc, what device are you using? I believe we have a fix in place (issue #123 ) for the first issue you reported here.

I believe we have a few fixes in place for the second issue you reported.

We should be releasing it soon.

**Comment by cjbeck** [comment]
I'm seeing strange issues as well. Time change issues. It looks like either my tablet or phone are causing data to be written to the DB with the wrong time. The original fix (in the issue that you reference above) did work for the uploading, but that was before the time change. I just uploaded logs from the tablet via the feedback menu. We're trying the "disconnect for an hour" fix on the phone now (it's at school with my daughter), so we'll see how things look after that's plugged back in.

**Comment by necroscope** [comment]
Hi,
The latest version of the uploader fixes the tablet issue.  Cjbeck can you please open a new issue for your problem as it is not related to the problem gangfc reported.  The problem gangfc reported is fixed.

Thanks!

**Comment by necroscope** [comment]
The latest version of the uploader fixes the tablet issue. Cjbeck can you please open a new issue for your problem as it is not related to the problem gangfc reported. The problem gangfc reported is fixed.
