### ISSUE TITLE
REST doesn't try to POST if API_SECRET contains special characters

### ISSUE THREAD

**Issue by scottleibrand** [nightscout/android-uploader#148]
I have a randomly-generated API_SECRET containing special characters (# and ]) that worked fine in Cookie Monster.  But upon upgrading to Dreamsicle, if my API_SECRET contains either of those characters (and REST uploads are enabled), the android-uploader fails to even display the reading or graph from the CGM, and does not even attempt a POST.

To reproduce, put in an API_SECRET like #h]asfasfdasdfasdfasdf via http://nightscout.github.io/pages/configure/, and auto-configure the android-uploader with the QR code.  (When I tried to enter it manually, Dreamsicle complained my URL was invalid, but it didn't complain when the URL came from the Cookie Monster upgrade or via the QR code.)  Plug in the CGM.  It will show the USB and Clock icons green, but the Upload and Dex Battery icons red, and will fail to display a BG or arrow, or any new dots on the graph.  If you tcpdump on the server the REST URL is pointing to, you also won't see any attempt to POST.

Ideally, we should allow API_SECRETs to contain special characters, as they could in Cookie Monster.  If that isn't possible, we should do REST URL syntax checking and present an error to the user any time an unsupported API_SECRET is present, not just when they first enter it.

**Comment by bewest** [comment]
Oops, didn't mean to mark it as fixed, per se, I have no idea if it's fixed, buthttp://nightscout.github.io/pages/configure/ 

Looks like REST part is not working actually.

**Comment by ktind** [comment]
Per [RFC 3986](https://tools.ietf.org/html/rfc3986#section-2.2) a # is a reserved character. It looks like the configuration page correctly encodes it.

We should be able to fix this at runtime using [URLEncoder](http://developer.android.com/reference/java/net/URLEncoder.html).

**Comment by ktind** [comment]
Fixed in Alpha builds. Gives user a warning if they do not enter a % encoded URL in the uploader.
