### ISSUE TITLE
Sometimes data is uploaded with PST, sometimes with MST, causes issues

### ISSUE THREAD

**Issue by cjbeck** [nightscout/android-uploader#157]
I haven't quite figured out why yet, but sometimes the android uploader (on the same device) uploads data in MST (seems to be after charging?), and to fix it, I can restart the application and it will start uploading data in PST. I'm thinking this has something to do with all of the time change issues that we've had previously, but i'm not certain.

Let me know if there are any steps you'd like me to take. I can fix it by restarting the app and removing all the entires that are in MST, but it's a pain. :)

**Comment by ELUTE** [comment]
Is auto timezone turned off for your uploader?

**Comment by cjbeck** [comment]
Are you talking about auto timezone on the phone itself? It _is_checked, should it not be?

**Comment by ELUTE** [comment]
Yes. Please uncheck it and see if that resolves the issue.

**Comment by cjbeck** [comment]
Yea, I unchecked it, so we'll see... I'm having a similar issue on the Tablet, so I'll make the same change there and see if it helps.

**Comment by cjbeck** [comment]
yea, this has fixed my issue. So, does this mean that some of the cell towers have not updated their TZ correctly?

**Comment by ktind** [comment]
I suspect this is an issue with the latest version of Joda-Time android that we updated to recently. I've seen it jump but in doing so it isn't actually between MST and PST it is between PDT and MST which are functionally equivalent right now. I know some people are seeing data in the future as well.

The next release makes a major change to the way we calculate time - it has its own challenges though.

I'll roll back to the previous version of Joda time and try to provide a dev build to see if it helps. Would you be willing to test again?

**Comment by cjbeck** [comment]
For sure, not a problem.

**Comment by ktind** [comment]
It turns out that we did not update Joda time. Please use the work around for now - we'll have a new release soon that should allow you to set auto update again.

**Comment by ktind** [comment]
Related to #164 . Closed with 9c118ea
