### ISSUE TITLE
0.2.0-alpha5 Pressing return button from app home screen closes app

### ISSUE THREAD

**Issue by jimsiff** [nightscout/android-uploader#159]
Pressing the return button from the app home screen closes the app rather than just minimizing it.  The Event log shows a new "Application Started" message for each time you use return to leave the app.  Pressing the Home button or switching tasks using the recent apps button does not behave this way.

If a receiver is connected when you press return, the app becomes unstable and may not work properly until you force close, uninstall, reboot, and reinstall the app.

**Comment by ktind** [comment]
Should be fixed with commit 54660b3

**Comment by ktind** [comment]
Closing this issue. Pleas re-open if you encounter it again.
