### ISSUE TITLE
Dreamsicle 0.1.13 Time Change Issue

### ISSUE THREAD

**Issue by denvergail** [nightscout/android-uploader#161]
Uploader phone (motoG 1st gen) set to manual time and manual time zone.  Traveled to a different timezone.  Unplugged phone from Dex.  Manually set time and time zone to correct/local time.  Set Dexcom receiver (NOT share) to correct local time.  Rebooted.  Plugged back together.  Error: Time change detected & red time icon.  Waited many minutes with no change.  Tried auto-time and zone.  No joy.  Reset everything back to my home time & zone - fixed it and I left it for the weekend.

**Comment by ktind** [comment]
Should be fixed in the latest alpha builds.
