### ISSUE TITLE
0.2.0-alpha2 Unexpected time jumps with auto time / timezone set

### ISSUE THREAD

**Issue by jimsiff** [nightscout/android-uploader#164]
I experienced a short and unexpected one hour time jump during the morning and then again in the evening while using a Moto G and the 0.2.0-alpha2 uploader app.  I have attached a screen shot of the Nightscout site, and an Excel spreadsheet showing the duplicate documents and other odd upload behavior.  The spreadsheet is sorted by document ID, so hopefully it's sorted in the order documents were written to Mongo.

I will update this issue after testing with auto time and timezone enabled on the 0.2.0-alpha5 (or newer) app.

![screen shot 2015-03-31 at 4 47 48 pm](https://cloud.githubusercontent.com/assets/6069420/6954786/772fcebe-d88a-11e4-894c-59cc98ccf611.png)

https://dl.dropboxusercontent.com/u/3823543/entries-rig2.03.31.15.xlsx

**Comment by ktind** [comment]
I replaced JodaTime Android with standard Joda time in Alpha 4  (Hash - 9c118ea). Let me know if this issue recurs.

**Comment by ktind** [comment]
Closing. Please re-open this issue if you encounter it again.
