### ISSUE TITLE
0.2.0-alpha5 Configuring MQTT crashes app

### ISSUE THREAD

**Issue by jimsiff** [nightscout/android-uploader#165]
When configuring MQTT for the first time (by hand) as soon as you enter the MQTT URI and press OK, the app crashes but saves the settings change.  The same crash occurs after entering the MQTT username and password, but again the setting changes are saved.  Once all three settings are set, the app appears to publish messages appropriately.

There should be logs in Tracepot.

**Comment by ktind** [comment]
Seems to be fixed in alpha6. Please re-open if you encounter it again.
