### ISSUE TITLE
0.2.0-alpha5 MQTT never reconnects to the broker after connection is dropped

### ISSUE THREAD

**Issue by jimsiff** [nightscout/android-uploader#167]
During periods of poor network connectivity, the MQTT connection dies and never re-establishes itself.  There is Tracepot feedback for this issue.  Must force close app, disconnect receiver, reboot and reconnect receiver to re-establish a connection again.

Edit: Not sure why the image is sideways.  Click on it and it shows correctly in the browser.

![img_1438](https://cloud.githubusercontent.com/assets/6069420/6979535/26a55188-d99a-11e4-93e1-8e8384c70566.JPG)

**Comment by ktind** [comment]
Should have been fixed in alpha6. Please re-open if you find otherwise.
