### ISSUE TITLE
Single Calibration Appears at Two Calibration Dots

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/android-uploader#178]
Single calibration (not a restart, just a regular calibration) shows up as two red calibration dots on the graph, each with a different Device (dexcom and dexcom_G4).

![calibration-double](https://cloud.githubusercontent.com/assets/9641700/7094747/0550f480-df79-11e4-9638-a67427f42654.png)

**Comment by ktind** [comment]
Which version of the uploader? I suspect this is one of the 0.2.0 alpha releases?

**Comment by oamyoamy** [comment]
You are absolutely right. This was my nighttime uploader... so not the current alpha. I didn't even think about that when spotting the oddity. Sorry for the false report.
