### ISSUE TITLE
Minimed CRC check

### ISSUE THREAD

**Issue by andyrozman** [nightscout/android-uploader#180]
Hi !
I was looking through code in minimed branch and I have one question about CRC method used... Minimed uses crc8 (calculateCRC8) for all internal decoding of data, but you use calculate16CCITT for checking CRC in page? Does this produce correct answer (between stored and calculated CRC)?

Andy

**Comment by bewest** [comment]
Yes, it's two different CRC's.

It appears that the frame CRCs are 8 bit while page CRCs are 16 bit.
They do in fact validate in decocare.

**Comment by bewest** [comment]
You may want to coordinate with @ktind as well as @GeoffWyche (https://github.com/GeoffWyche/RTDemo)
