### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by cgmnellanuvola** [nightscout/android-uploader#43]
As discussed with Ben and Kevin I would like to localize the three parts of Nightscout. I'm Italian and I'm supporting the Italian community in order to setup and manage Nightscout and I think it would beneficial for many to have a localized software.
I'm translating android-uploader in Italian and German via a German friend of mine.

I hope I'm using the right tool to start a discussion and keep track of changes, if not please let me know.

Ivan

**Comment by ktind** [comment]
This is ongoing so I'm going to go ahead and close the issue. Thank you for your contributions. :smiley:
