### ISSUE TITLE
Upload noise value from egv record when uploading unfiltered

### ISSUE THREAD

**Issue by scottleibrand** [nightscout/android-uploader#95]
If the user selects the preference to upload Sensor Data, we should also include the noise value (clean/light/medium/heavy) from the EGV record.  That value is used by the Dexcom to determine whether to display unfiltered (if noise=clean), filtered (if noise=light/medium) or ??? (if noise=heavy).

**Comment by ktind** [comment]
Just created [kl.noiseviarest](https://github.com/nightscout/android-uploader/tree/kl.noiseviarest). It still needs to be tested

@jasoncalabrese @rnpenguin

**Comment by jasoncalabrese** [comment]
Was just about to get setup to test the latest dev, I'll test this instead

**Comment by jasoncalabrese** [comment]
Started test using kl.noiseviarest uploading to rest and mongo, see `noise: 1` for both upload methods, couldn't be simpler.  I'll let it run for the rest of the night.

**Comment by YYGIRL** [comment]
Hey Ross - I think the noise values might be different? I've been testing
noise values on the pebble for quite some time.

Note I was testing the values for months from a special uploader that I was
using made with John's help. It passed the string, not the value, and I
always saw Clean, Light, Medium, or Heavy.

I'm now using your uploader, and getting the integer value. Based on what I
saw before, this is how it has been lining up : 1-clean, 2-light, 3-medium,
4-heavy, 5-unknown when in a warmup. I've never seen a 0 or 6.

On Sun, Feb 1, 2015 at 11:08 PM, Jason Calabrese <notifications@github.com>
wrote:

> Closed #95 <https://github.com/nightscout/android-uploader/issues/95>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nightscout/android-uploader/issues/95#event-228271161>
> .
>



-- 
*Join the Jack Attack!*
*Fight Type 1 Diabetes*
*Give to the JDRF - **www.jdrf.org* <http://www.jdrf.org>

**Comment by YYGIRL** [comment]
Jason - I'm now using your new code to test the three way option "only show
raw when noise". I'm in heavy noise right now, ???, but with a noise value
of 4. So when I set the three way option, it doesn't show me the raw
because I guess it assumes I'm not having heavy noise.

On Mon, Feb 2, 2015 at 3:52 PM, Christine Deltrap <
contact.christine@gmail.com> wrote:

> Hey Ross - I think the noise values might be different? I've been testing
> noise values on the pebble for quite some time.
>
> Note I was testing the values for months from a special uploader that I
> was using made with John's help. It passed the string, not the value, and I
> always saw Clean, Light, Medium, or Heavy.
>
> I'm now using your uploader, and getting the integer value. Based on what
> I saw before, this is how it has been lining up : 1-clean, 2-light,
> 3-medium, 4-heavy, 5-unknown when in a warmup. I've never seen a 0 or 6.
>
> On Sun, Feb 1, 2015 at 11:08 PM, Jason Calabrese <notifications@github.com
> > wrote:
>
>> Closed #95 <https://github.com/nightscout/android-uploader/issues/95>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nightscout/android-uploader/issues/95#event-228271161>
>> .
>>
>
>
>
> --
> *Join the Jack Attack!*
> *Fight Type 1 Diabetes*
> *Give to the JDRF - **www.jdrf.org* <http://www.jdrf.org>
>



-- 
*Join the Jack Attack!*
*Fight Type 1 Diabetes*
*Give to the JDRF - **www.jdrf.org* <http://www.jdrf.org>

**Comment by jasoncalabrese** [comment]
You're using the currently uploaders, do you see noise=4 in the /pebble endpoint?  I saw it work with noise=1, but haven't had more noise since then to test

**Comment by YYGIRL** [comment]
Yes, I am using the current uploader and see noise=4 in the pebble
endpoint. I've seen everything from 1-5 for the past couple of weeks.

On Mon, Feb 2, 2015 at 4:00 PM, Jason Calabrese <notifications@github.com>
wrote:

> You're using the currently uploaders, do you see noise=4 in the /pebble
> endpoint? I saw it work with noise=1, but haven't had more noise since then
> to test
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nightscout/android-uploader/issues/95#issuecomment-72536740>
> .
>



-- 
*Join the Jack Attack!*
*Fight Type 1 Diabetes*
*Give to the JDRF - **www.jdrf.org* <http://www.jdrf.org>

**Comment by jimsiff** [comment]
Does the 0.1.12 uploader send noise via REST, or just Mongo?  I don't see noise in my /pebble endpoint.  I only use REST at the moment.

**Comment by trhodeos** [comment]
Should send via both.

**Comment by jasoncalabrese** [comment]
I'm getting noise for rest, but I built from the code so it's possible it's
not exactly the same as what was released.

Guess that explains why you didn't see any raw data

**Comment by YYGIRL** [comment]
I don't get noise for REST either, only mongo.

On Mon, Feb 2, 2015 at 9:20 PM, Jason Calabrese <notifications@github.com>
wrote:

> I'm getting noise for rest, but I built from the code so it's possible
> it's
> not exactly the same as what was released.
>
> Guess that explains why you didn't see any raw data
> On Feb 2, 2015 6:17 PM, "Tyler Rhodes" <notifications@github.com> wrote:
>
> > Should send via both.
> >
> > On Mon, Feb 2, 2015 at 5:57 PM, Jim Sifferle <notifications@github.com>
> > wrote:
> >
> > > Does the 0.1.12 uploader send noise via REST, or just Mongo? I don't
> see
> > > noise in my /pebble endpoint. I only use REST at the moment.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/nightscout/android-uploader/issues/95#issuecomment-72577946>
>
> >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/nightscout/android-uploader/issues/95#issuecomment-72580152>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nightscout/android-uploader/issues/95#issuecomment-72580425>
> .
>



-- 
*Join the Jack Attack!*
*Fight Type 1 Diabetes*
*Give to the JDRF - **www.jdrf.org* <http://www.jdrf.org>

**Comment by trhodeos** [comment]
If you are on Dreamsicle, you should get noise via rest. Check out 'noise'
in the recent commits found here:
https://github.com/nightscout/android-uploader/commits/0.1.12

**Comment by jasoncalabrese** [comment]
I tested that PR, saw there was since confusion in the support group about
the direct download link maybe that was the cause?

**Comment by YYGIRL** [comment]
OK, have latest dreamsicle uploader and now getting noise via REST. 0.1.12.
Thank you.

Note the values have not changed to anything different. 1-clean, 2-light,
3-medium, 4-heavy, 5-unknown when in a warmup. I've never seen a 0 or 6.

On Mon, Feb 2, 2015 at 10:33 PM, Jason Calabrese <notifications@github.com>
wrote:

> I tested that PR, saw there was since confusion in the support group about
> the direct download link maybe that was the cause?
> On Feb 2, 2015 7:30 PM, "Tyler Rhodes" <notifications@github.com> wrote:
>
> > If you are on Dreamsicle, you should get noise via rest. Check out
> 'noise'
> > in the recent commits found here:
> > https://github.com/nightscout/android-uploader/commits/0.1.12
> >
> > On Mon, Feb 2, 2015 at 6:26 PM, YYGIRL <notifications@github.com>
> wrote:
> >
> > > I don't get noise for REST either, only mongo.
> > >
> > > On Mon, Feb 2, 2015 at 9:20 PM, Jason Calabrese <
> > notifications@github.com>
> > >
> > > wrote:
> > >
> > > > I'm getting noise for rest, but I built from the code so it's
> possible
> > > > it's
> > > > not exactly the same as what was released.
> > > >
> > > > Guess that explains why you didn't see any raw data
> > > > On Feb 2, 2015 6:17 PM, "Tyler Rhodes" <notifications@github.com>
> > > wrote:
> > > >
> > > > > Should send via both.
> > > > >
> > > > > On Mon, Feb 2, 2015 at 5:57 PM, Jim Sifferle <
> > notifications@github.com>
> > >
> > > > > wrote:
> > > > >
> > > > > > Does the 0.1.12 uploader send noise via REST, or just Mongo? I
> > don't
> > > > see
> > > > > > noise in my /pebble endpoint. I only use REST at the moment.
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > > >
> > > >
> > >
> >
> https://github.com/nightscout/android-uploader/issues/95#issuecomment-72577946>
>
> >
> > >
> > > >
> > > > >
> > > > > > .
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/nightscout/android-uploader/issues/95#issuecomment-72580152>
>
> >
> > >
> > > >
> > > > > .
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/nightscout/android-uploader/issues/95#issuecomment-72580425>
>
> >
> > >
> > > > .
> > > >
> > >
> > >
> > >
> > > --
> > > *Join the Jack Attack!*
> > > *Fight Type 1 Diabetes*
> > > *Give to the JDRF - **www.jdrf.org* <http://www.jdrf.org>
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/nightscout/android-uploader/issues/95#issuecomment-72581004>
>
> >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/nightscout/android-uploader/issues/95#issuecomment-72586697>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nightscout/android-uploader/issues/95#issuecomment-72586925>
> .
>



-- 
*Join the Jack Attack!*
*Fight Type 1 Diabetes*
*Give to the JDRF - **www.jdrf.org* <http://www.jdrf.org>

**Comment by jimsiff** [comment]
I upgraded my uploaders via the Play Store.  The version says 0.1.12 with no beta suffix.  Is the Play Store build possibly different?

**Comment by trhodeos** [comment]
It's possible, but I'm 99.99% sure they are the same. Do you have 'Sensor
Data' checked in the preferences menu?

**Comment by jasoncalabrese** [comment]
I think I may have just found a bug that could explain this, seems that the raw data isn't uploaded (rest or mongo) when you use Gap Sync

**Comment by jimsiff** [comment]
@trhodeos I do have sensor data checked.  I can see raw on my wip/enable-raw and iob-cob sites, but no noise in the /pebble output, and no raw for my enable-raw site with the "when noise is present" option selected.  I'm going to verify tonight that I'm running the most current version available via Play Store.  It's possible I still have a beta loaded, though I'd be surprised.

Here's an example from my Pebble page:

{"status":[{"now":1423096722095}],"bgs":[{"sgv":"88","bgdelta":-5,"trend":4,"direction":"Flat","datetime":1423096566000,"filtered":111728,"unfiltered":104944,"rssi":187,"battery":"14"}],"cals":[{"_id":"54d241151713124c1ba45e85","device":"dexcom","scale":0.9506484273057073,"dateString":"Wed Feb 04 07:56:08 PST 2015","date":1423065368000,"type":"cal","intercept":30000,"slope":837.05674241743}]}
